---
- name: Install required s/w's on devserver
  hosts: devserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: git,b: present,c: yes}
        - {a: openjdk-11-jdk,b: present,c: no}
        - {a: maven,b: present,c: no}
- name: Install required s/w's on qaserver
  hosts: qaserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: git,b: present,c: yes}
        - {a: openjdk-11-jdk,b: present,c: no}
        - {a: tomcat9,b: present,c: no}
        - {a: tomcat9-admin,b: present,c: no}
- name: Install required s/w's on prodserver
  hosts: prodserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: no}
- name: Continuous Download and Continuous Build
  hosts: devserver
  tasks:
    - name: Download dev code from github
      git:
        repo: https://github.com/sudarshansw7/mymaven.git
        dest: dev-git
    - name: Create an artifact from the above code
      shell: cd dev-git;mvn package
