---
- name: call multiple childplaybooks for apache
  hosts: all
  tasks:
    - name: call multiple playbooks
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml

...
