---
- name: creating user
  hosts: servers
  tasks:
    - name: user creation
      user:
        name: vidya
        password: sree
        home: /tmp/vidya
        uid: 3333
        shell: /bin/bash
        comment: "A normal user"

...


