---
- name: Create users and copy files into users home dir
  hosts: all
  tasks:
    - name: create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Ramesh,b: Priya,c: /home/Ramesh}
        - {a: Rajesh,b: Priya,c: /tmp/Rajesh}
    - name: copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/Ramesh}
        - {a: /etc/group,b: /tmp/Rajesh}
...
